language: go
go:
- 1.12
script: go vet
before_deploy:
- ./release.sh
deploy:
  provider: releases
  api_key:
    secure: drFLCdqzgcKNkYl1mFlOQmvjvHU/TC+ncnWy1qlV+BYl2yN1QV8hCXNFEHSdicxK14ROoQFwqt4z1kjyvcQIvygu3BTX9LeZ5C5FVVKHED/iW7KF/kMibAxWSXOai1K3Tr9OEgPcXZqchbGRkmNMlrSuyYP4JKOxEEbmMd9U46zua0ymY1iWebT6lTrP4Ritsr7W4diqgRx5BY17wvm2eg3nf3EVuWKfTKOpwE7cjibu3GfmsFrK5SFBfvax60yshAHYtiGU7IKoA/7IrHZEA8EMBqmDeTrMfDGPCVBYaw5kNbObl7rZ07KN5WHL5weHAQFDRl5XYN5tVF9imWgBu2RarJeWQ+plFIMqEq25GKXv5mckQAkoNY2FAAt+k+bZtkBAowKuAoZNVixBUYjtbe6LxxyTQxInhtQyn6HlCen7LFDkjCYoTvgzenpmVd2DqFjUNTCGVAYADwczSgucH3gdaxOJvN8WsL/yjLwBUa9IrGpf52GzyYCBhYSU/uYPOHAWsDDuqLvl3Ft4hKAI60/rnR3skfmJbM7LS7T0uhtL/nXTJJj0bDqHBgIDiJHey1JZjgy5Bjq25CTrvYjxfqVsovXRlCORaQfqqenWrL+UV3W2LUVU4SJhD6o841XXgG5vEEB9Uimnt8KxZOW/HRXGXeu7qF9ze10GH8zq7Ww=
  skip_cleanup: true
  file:
    - release/yaml2json-darwin-amd64
    - release/yaml2json-darwin-amd64.sha256
    - release/yaml2json-linux-amd64
    - release/yaml2json-linux-amd64.sha256
  on:
    repo: wakeful/yaml2json
    branch: master
    tags: true
